# fly.toml app configuration file generated for rotator on 2025-02-28T11:57:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rotator'
swap_size_mb = 512

[env]
DEFAULT_COUNTRY_CODE = "US"

[deploy]
release_command = "yarn run drizzle-kit migrate"
strategy = "bluegreen"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
grace_period = "15s"
interval = "30s"
method = "GET"
path = "/healthz"
protocol = "http"
timeout = "5s"

[[vm]]
memory = "512mb"
