/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "APP_URL_BASE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DEFAULT_COUNTRY_CODE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MigratorFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OAUTH2_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAUTH2_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAUTH2_SERVER_BASE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Rotator": {
      "type": "sst.aws.React"
      "url": string
    }
    "SECRET_KEY_BASE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SMTP_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TWILIO_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TWILIO_SID": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}