// generated by react-router-hono-server/dev
import { createHonoServer } from "react-router-hono-server/node";
import TwilioClient from "twilio";
import "react-router";
import "dotenv/config";
import { validateRequest } from "twilio/lib/webhooks/webhooks";

async function validateTwilioWebhook(request: Request) {
  const twilioSignature = request.headers.get("X-Twilio-Signature");
  if (!twilioSignature) {
    throw new Response(
      "No signature header error - X-Twilio-Signature header does not exist, maybe this request is not coming from Twilio.",
      {
        status: 400,
        headers: {
          "Content-Type": "text/plain",
        },
      }
    );
  }

  const webhookUrl = new URL(request.url);
  if (request.headers.get("X-Forwarded-Proto")) {
    webhookUrl.protocol = request.headers.get("X-Forwarded-Proto") ?? "";
  }

  const params = Object.fromEntries((await request.formData()).entries());

  const isValid = validateRequest(
    process.env.TWILIO_AUTH_TOKEN ?? "",
    twilioSignature,
    webhookUrl.toString(),
    params
  );

  if (!isValid) {
    throw new Response("Twilio Request Validation Failed.", {
      status: 403,
      headers: {
        "Content-Type": "text/plain",
      },
    });
  }
}

declare module "react-router" {
  interface AppLoadContext {
    twilioClient: TwilioClient.Twilio;
    validateTwilioWebhook: typeof validateTwilioWebhook;
  }
}

export default await createHonoServer({
  getLoadContext(c, options) {
    const twilioClient = TwilioClient(
      process.env.TWILIO_SID,
      process.env.TWILIO_AUTH_TOKEN
    );
    return { twilioClient, validateTwilioWebhook };
  },
});
